{
 "title": "Ingress Logs",
 "description": "Application access logs from the load balancer (ingress controller).\n",
 "tags": [
  "nais",
  "application",
  "ingress"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "query": "dev : dev,prod : prod" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "namespace",
    "query": "label_values(nginx_ingress_controller_requests, namespace)"
   },
   {
    "name": "host",
    "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\"}, host)"
   },
   { "name": "search" },
   {
    "name": "status",
    "query": "All : .*,2xx : 2\\d{2},3xx : 3\\d{2},4xx : 4\\d{2},5xx : 5\\d{2}"
   },
   {
    "name": "method",
    "query": "All : .*,GET : GET,POST : POST,PUT : PUT,PATCH : PATCH,DELETE : DELETE,HEAD : HEAD,OPTIONS : OPTIONS"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  increase(\n    nginx_ingress_controller_requests{\n      namespace=~\"$namespace\",\n      host=~\"$host\",\n      status=~\"$status\",\n      method=~\"$method\",\n    }[$__interval]\n  )\n)\n",
     "legendFormat": "{{status}}\n"
    }
   ]
  },
  {
   "title": "Request Dureation",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le, host) (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        namespace=~\"$namespace\",\n        host=~\"$host\",\n        status=~\"$status\",\n        method=~\"$method\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "$host 95%\n"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, host) (\n    rate(\n      nginx_ingress_controller_request_duration_seconds_bucket{\n        namespace=~\"$namespace\",\n        host=~\"$host\",\n        status=~\"$status\",\n        method=~\"$method\",\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "$host 99%\n"
    }
   ]
  },
  {
   "title": "Ingress Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{\n  service_name=\"nais-ingress\",\n  service_namespace=\"$namespace\"\n}\n  |= `$search`\n  | json\n  | __error__=``\n  | url_domain = `$host`\n  | http_request_method =~ `$method`\n  | http_response_status_code =~ `$status`\n  | line_format `{{.remote_addr}} {{.message}} {{.http_response_status_code }} {{.destination_address}} {{.user_agent_original}}`\n"
    }
   ]
  }
 ]
}